name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
   
    - name: Build the Docker image
      run: | 
        docker build -t abhinavthorat15/student_api .
        docker push abhinavthorat15/student_api


  delivery:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Run_image
      run: |
        docker pull abhinavthorat15/student_api:latest
        docker run -p 8080:8080 abhinavthorat15/student_api:latest  